[project]
name = "geoprice-backend"
version = "0.1.0"
description = "FastAPI Backend for Spatio-Temporal AI"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "psycopg2-binary",
    "redis",
    "minio",
    "arq",
    "httpx",
    "passlib[bcrypt]",
    "bcrypt",
    "python-jose[cryptography]",
    "python-multipart",
    "email-validator",
    "websockets"
]